### ISSUE TITLE
Extract icon data to its own package?

### ISSUE THREAD

**Issue by simonhildebrandt** [phosphor-icons/phosphor-home#105]
My current employer loves this icon set - we're using it heavily in the redesign of our whole platform. So, thanks so much for making them, and letting us use them. :)

We've even built a custom icon picker - which posed a few challenges when we tried to find an exhaustive list of the icons available. 😓  We finally found what we needed in this (phosphor-home) package - which (as I understand it) is the basis for the search on the main Phosphor site. Awkwardly, that means we're installing this whole package just to get one piece of data from it (plus types) and (also awkwardly) the package has a debug message ("XXX Icons") that now appears for us in dev.

The data in question is super useful by itself, so I reckon it should be its own package. How would the maintainers feel about a task to extract it, for inclusion wherever? We'd be happy to try taking on this task ourselves, if that'd help. :)

Thanks again. :)

**Comment by rektdeckard** [comment]
You're essentially looking for the catalog information -- icon names, categories, tags that we use on our homepage -- independent of implementation? I might consider extracting it into its own package, but I'm unfortunately pretty tied up right now, and it's not something I can do immediately.

We *do* have an undocumented public API available at https://api.phosphoricons.com which serves essentially the data that you're looking for, but it's really suitable only for build-time use (too slow for live applications, and not built for that kind of traffic). You're welcome to use it in that manner.

If you want some more information on it, or want to discuss further, please send us an email at hello@phosphoricons.com.

**Comment by simonhildebrandt** [comment]
Thanks for the quick response @rektdeckard . Yep, the catalogue is what we're after. We're able to import them from `phosphor-home/tree/master/src/lib/icons.ts` but as mentioned, that involves installing the whole package, and also scores us some debug in dev. 😅  

(Thanks also for the API idea, but I wouldn't want to add an API dependency for our build process if I can help it, both for the load on that API and the potential brittleness involved.)

Will you email about a potential PR for the new, isolated, package.

**Comment by rektdeckard** [comment]
FYI @simonhildebrandt, we now have the [@phosphor-icons/core](https://github.com/phosphor-icons/core) package, which exposes our catalog, with tags, categories and everything, in a public NPM package 👍
