### ISSUE TITLE
Icon Request: GitHub

### ISSUE THREAD

**Issue by Schwefelhexa** [phosphor-icons/phosphor-home#11]
Hi, I love your icons and really enjoy using them!
I'm building a simple open-source website and would like to add a link to its GitHub.

**Describe the requested icon**
A GitHub icon.

**Screenshots**
![](https://image.flaticon.com/icons/svg/25/25231.svg)
![](https://image.flaticon.com/icons/png/512/889/889192.png)

**Additional context**
I wasn't sure if this is allowed in terms of IP, but I've found a lot of free icons reinterpreting GitHub, so I assume it is legal.

**Comment by rektdeckard** [comment]
Thanks @Schwefelhexa, it's definitely something we planned on. You can expect to see a GitHub icon in a future release!

**Comment by Schwefelhexa** [comment]
Great to hear! Looking forward to it.
