### ISSUE TITLE
Icon request: thermometer and humidity

### ISSUE THREAD

**Issue by j-flat** [phosphor-icons/phosphor-home#12]
The available icon set is amazing, but there's one icon missing from building great looking home weather station UI and it's thermometer icon.  Would be great addition, since e.g. weather related icons already exist. 

Existing drop icon would work for humidity usage, but slight modification with %-sign would make it even more ideal fit for humidity data.

**Comment by rektdeckard** [comment]
Thanks so much! You'll be happy to hear thermometer icons are coming soon. We'll add a humidity icon to the list.

**Comment by rektdeckard** [comment]
Thermometer has been added to all libraries as of `v1.1.0` 🌡. There is also a new `drop-half` icon that could suit your needs for humidity.

**Comment by j-flat** [comment]
That's amazing!! :) They're beautiful! Great job 👍
