### ISSUE TITLE
Icon request: teacher/chalkboard/seminar

### ISSUE THREAD

**Issue by rossjrw** [phosphor-icons/phosphor-home#13]
I'm trying to pick an icon to represent my community's seminars. I've grown really quite attached to the duotone Phosphoricons, so it's a shame that there's nothing education-based in there, not even a graduation cap. In the meantime I'm using `puzzle-piece`.

FontAwesome has both a chalkboard and a chalkboard+teacher:

<p align="center"><img width="300" src="https://user-images.githubusercontent.com/29130152/100845660-7e513000-3475-11eb-8188-1e635244ab0a.png"></p>

Many thanks, and thanks to the both of you for this very useful project.

**Comment by rektdeckard** [comment]
Thanks for the feedback, will add this to the list! In the mean time could any of the `book` or `note` icons work for you?

**Comment by rossjrw** [comment]
Thanks for the suggestion! Unfortunately we're a writing community so either of those would be ambiguous with other links in the same component. I appreciate the thought, though!

**Comment by rektdeckard** [comment]
`chalkboard`, `chalkboard-simple`, `chalkboard-teacher`, and `graduation-cap`  added in 1.2.0!
