### ISSUE TITLE
Loading State

### ISSUE THREAD

**Issue by 1qlee** [phosphor-icons/phosphor-home#14]
**Describe the requested icon**
An icon that represents a loading state. Like a circle of dots or a circle with a notch so you can animate it to show loading. (I couldn't find anything that resembled this, correct me if I'm wrong.)

**Screenshots**
![image](https://user-images.githubusercontent.com/13893852/101116454-228cc100-35b3-11eb-9a4e-b3ca035a385b.png)
![image](https://user-images.githubusercontent.com/13893852/101116473-2caebf80-35b3-11eb-9497-d25cd2c1b006.png)

**Additional context**
Love the library. Thanks for your hard work!

**Comment by rektdeckard** [comment]
`spinner` and `spinner-gap`  added in 1.2.0!
