### ISSUE TITLE
MotorcycleIcon

### ISSUE THREAD

**Issue by wendylw** [phosphor-icons/phosphor-home#143]
**Describe the requested icon**
Food delivery type

**Screenshots**
![image](https://user-images.githubusercontent.com/4416839/174043711-8a1d92f6-2078-42d8-9875-778b2fb05cfd.png)

**Additional context**
Add any other context here.

**Comment by Ellarddekoeijer** [comment]
Yes please, I really need this too!

**Comment by rektdeckard** [comment]
Duplicate of #137

**Comment by rektdeckard** [comment]
Added `motorcycle`, `moped`, `moped-front`, `scooter` in v2.0.0
