### ISSUE TITLE
Suggestion: Trophy/Challenge Cup/Leaderboard/Tournament Icons

### ISSUE THREAD

**Issue by ajaypillay** [phosphor-icons/phosphor-home#15]
**Describe the requested icon**
I think these icons would be extremely useful especially for tournaments, competitions, or any form of leaderboard. These are good for virtual "awards" as well (crowns, medals, etc).

**Screenshots**
![image](https://user-images.githubusercontent.com/917752/102007910-cf133380-3d67-11eb-9cc7-459bc7c1dd69.png)
![image](https://user-images.githubusercontent.com/917752/102007914-e0f4d680-3d67-11eb-844d-a5cbb0edf0ee.png)
![image](https://user-images.githubusercontent.com/917752/102007922-f2d67980-3d67-11eb-8303-6b4e9f4195a9.png)
![image](https://user-images.githubusercontent.com/917752/102007929-fe29a500-3d67-11eb-8453-8d013ed08797.png)
![image](https://user-images.githubusercontent.com/917752/102007937-0b469400-3d68-11eb-99f8-7b0c838dd7a3.png)
![image](https://user-images.githubusercontent.com/917752/102007942-17325600-3d68-11eb-897a-1f7f9d0bb9a5.png)

**Additional context**
Thank you, this is a fantastic icon library. :-)

**Comment by rektdeckard** [comment]
Thanks @ajaypillay, good suggestions. At the moment we only have a `medal` icon. Will keep these on the short list.

**Comment by rektdeckard** [comment]
`trophy`, `crown`, and `crown-simple`  added in 1.2.0! We also already have a `medal` icon.
