### ISSUE TITLE
Blank/Empty/Null Icon

### ISSUE THREAD

**Issue by michaelwelch** [phosphor-icons/phosphor-home#16]
**Describe the requested icon**

Sometimes, when some items in a complex template have or don't have an icon, it may be beneficial to load them with a 'blank' icon to keep code simple instead adjusting visibility or opacity.

**Screenshots**

Super simple: just a empty icon that could support the same attributes (mainly size) that normal icons could support.

**Comment by rektdeckard** [comment]
Interesting idea. Personally I would spring for something simple like:
```jsx
<svg xmlns="http://www.w3.org/2000/svg" height={size} width={size}></svg>
```
But I could see the need for a library solution for cases where you wanted to make use of  Context or composition. Will definitely consider adding it. In the mean time, you can make your own, since we give you all the icon dependencies as public exports:

```tsx
import { forwardRef, memo, useContext } from "react";
import { IconProps, IconContext } from "phosphor-react";

const EmptyIcon = forwardRef<SVGSVGElement, IconProps>(
  memo((props, ref) => {
    const { color, size, weight, mirrored, children, ...restProps } = props;
    const {
      color: contextColor,
      size: contextSize,
      weight: contextWeight,
      mirrored: contextMirrored,
      ...restContext
    } = useContext(IconContext);

    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        width={size ?? contextSize}
        height={size ?? contextSize}
        fill={color ?? contextColor}
        viewBox="0 0 256 256"
        transform={mirrored || contextMirrored ? "scale(-1, 1)" : undefined}
        {...restContext}
        {...restProps}
      >
        {children}
        <rect width="256" height="256" fill="none" />
      </svg>
    );
  })
);

export default EmptyIcon;
```

Here I included the Context and seemingly irrelevant props in the case you would want to do something conditionally with them, but you could leave them out.

**Comment by rektdeckard** [comment]
A more minimal example that's still context-aware:

```tsx
import React, { forwardRef, memo, useContext } from "react";
import { IconProps, IconContext } from "../lib";

const EmptyIcon = forwardRef<SVGSVGElement, IconProps>(
  memo(({ size }, ref) => {
    const { size: contextSize } = useContext(IconContext);

    return (
      <svg
        ref={ref}
        xmlns="http://www.w3.org/2000/svg"
        width={size ?? contextSize}
        height={size ?? contextSize}
        fill="none"
      />
    );
  })
);

export default EmptyIcon;
```

**Comment by rektdeckard** [comment]
I just realized I thought this issue was on the `phosphor-react` library, and the example reflects that. But I guess the point still stands, it's an interesting idea but I'm not totally warm to including it yet.

**Comment by wayne-shih** [comment]
alternatively, another way of thinking of this is the `.notdef` (aka. tofu) glyph in fonts...
https://docs.microsoft.com/en-us/typography/opentype/spec/recom#glyph-0-the-notdef-glyph 
which is what normally gets displayed when a glyph requested isn't in the font 

visually could be something like this: 
<a href="https://blogs.adobe.com/CCJKType/2016/05/tofu-or-not-tofu.html"><img width="200" alt="image" src="https://blogsimages.adobe.com/CCJKType/files/2016/05/notdef.jpg"></a>

pro of this would be if phosphor gets converted into (web) icon fonts as `.notdef` is a required glyph (although sometimes left blank visually, so it looks like a space)

**Comment by rektdeckard** [comment]
This is the way. Phosphor already is an icon font, and we currently use a blank space for `.notdef`, but this is much better and solves both problems.

**Comment by rektdeckard** [comment]
`placeholder` icon  added in 1.2.0!
