### ISSUE TITLE
CDN Script not loading

### ISSUE THREAD

**Issue by josephgeorgegit** [phosphor-icons/phosphor-home#164]
Not sure if this is a bug or something maybe I could receive help with but doesn't hurt to ask

The script import is returning to me a 520 error, is there a server failure or something at the moment?

### how to recreate
using the script in the head of html file
`<script src="https://unpkg.com/phosphor-icons"></script>`

gets me this
![image](https://user-images.githubusercontent.com/72976469/180783602-853611b4-589c-4df0-9c4a-652687e8b857.png)

Note:
Sometimes it loads but most of the time its not loading at all and causing very slow load times both on remote server and local servers
This first happened maybe an hour ago and has stayed the same since

Thank you for any support

**Comment by rom013** [comment]
i'm having the same problem when using cdn script

**Comment by rektdeckard** [comment]
Unpkg had several outages around this time. I think this issue resolved itself.
