### ISSUE TITLE
Wine Glass Icon

### ISSUE THREAD

**Issue by elise-lcdb** [phosphor-icons/phosphor-home#171]
**Describe the requested icon**
To go with my request for a wine bottle, I think there should also be a wine glass. Currently there is just a Martini Glass available 

**Screenshots**
![CleanShot 2022-08-19 at 11 14 24](https://user-images.githubusercontent.com/31904512/185587195-7c3268ca-9048-4dd1-b3df-20a46d12e6a8.png)

**Comment by tobias-fried-qatalog** [comment]
We have the `wine` icon already, which is a wine glass
