### ISSUE TITLE
Icon Request: Snapchat

### ISSUE THREAD

**Issue by fozdemir40** [phosphor-icons/phosphor-home#19]
**Describe the requested icon**
Please a request for Snapchat logo icon, my client uses Snapchat for marketing. I develop their website, so I want to add a Snapchat link.

**Screenshots**
![f7da0b66509b44da703d8d224369223f](https://user-images.githubusercontent.com/26762465/102788339-c55e8100-43a2-11eb-98f8-b92d432db5a2.png)

Additional context
This library is a blessing, thank you for the hard work. Donating soon!

**Comment by rektdeckard** [comment]
`snapchat-logo`  added in 1.2.0!
