### ISSUE TITLE
Icon Request [Screen Share]

### ISSUE THREAD

**Issue by adi2381** [phosphor-icons/phosphor-home#21]
Screen share icon please, love your work so much!

**Comment by rektdeckard** [comment]
Thanks @adi2381. Did you see the `screencast`,  `airplay`, and `monitor-play` icons? One of those might suit your needs. If not, please follow the request template and add screenshots / supporting images of what you're requesting.

**Comment by adi2381** [comment]
@rektdeckard Sorry for the late reply. I hope you're doing well. Yes, the above-mentioned icons did the work for me. Thanks a lot!

**Comment by rektdeckard** [comment]
Great. Will work on better tagging so they're easier to find in future.
