### ISSUE TITLE
Icon Request: verified + unverified

### ISSUE THREAD

**Issue by wayne-shih** [phosphor-icons/phosphor-home#23]
## Describe the requested icon

Similar to `check-circle` and `question` but with wavy circle

## Screenshots

<img width="300" alt="image" src="https://user-images.githubusercontent.com/51947763/103834857-7aa27000-50e9-11eb-81fc-71c218b2f93c.png">   <img width="400" alt="image" src="https://user-images.githubusercontent.com/51947763/103835024-fa303f00-50e9-11eb-8bba-28cc9c696672.png">

## Existing implementations

<img width="204" alt="image" src="https://user-images.githubusercontent.com/51947763/103834369-0f0bd300-50e8-11eb-93bc-a455f42d1308.png">

<img width="589" alt="image" src="https://user-images.githubusercontent.com/51947763/103834388-2054df80-50e8-11eb-82c2-ed8efa33ee1a.png">

<img width="220" alt="image" src="https://user-images.githubusercontent.com/51947763/103834481-6742d500-50e8-11eb-98c1-e88c2c282833.png">

<img width="402" alt="image" src="https://user-images.githubusercontent.com/51947763/103834638-dddfd280-50e8-11eb-8bc1-8c8595e5ce8c.png">

**Comment by rektdeckard** [comment]
Dig it! Thanks for the request.

**Comment by rektdeckard** [comment]
A number of variants were just added in 1.2.0! `circle-wavy`, `circle-wavy-check`, `circle-wavy-question`, `circle-wavy-warning`.
