### ISSUE TITLE
Icon Request: Picture-in-picture (PiP)

### ISSUE THREAD

**Issue by se34k** [phosphor-icons/phosphor-home#24]
**Describe the requested icon**
A picture-in-picture icon (as the one seen for example when you play videos with Firefox or Opera) to change a video into a smaller format version that is usually displayed in a corner of the screen to allow for browsing content while simultaneously watching a video.
It could for example be used in a video chat app or on any website that offers video playback.

**Screenshots**

Picture-in-picture button in Firefox (also note the PiP icon in the YouTube player controls):

![image](https://user-images.githubusercontent.com/76045565/103907869-1b9d2500-5102-11eb-9ffb-9d8e126288cc.png)

**Existing implementations**

The icon used in firefox:

![image](https://user-images.githubusercontent.com/76045565/103907170-358a3800-5101-11eb-988c-abe2abdfa73f.png) 

Material icons for picture-in-picture mode:

![image](https://user-images.githubusercontent.com/76045565/103907602-c3feb980-5101-11eb-89d8-7e337e4744c3.png)

**Comment by rektdeckard** [comment]
Great idea, thanks for the request 👌

**Comment by rektdeckard** [comment]
`PictureInPicture` added in 1.2.0!
