### ISSUE TITLE
enable/disable `stroke-linecap` and `stroke-linejoin`

### ISSUE THREAD

**Issue by AustinGil** [phosphor-icons/phosphor-home#25]
Hey, fantastic job on the icons and website. I have one idea for an enhacement. It would be really cool if you could provide checkboxes to enable/disable `stroke-linecap` and `stroke-linejoin`

**Comment by rektdeckard** [comment]
Thanks for the feedback! 

We want to toe the line between being highly tweakable, yet still having a cohesive style to the icons — and variable caps/joins is a thought we toyed with and ultimately decided against. Some icons are constructed with border radius, or organic curves that don't translate well when the overall "soft" style of the rounded caps and joins is removed. That being said, the stroke data is all there if you need to customize a "sharp" style for your own needs.

Closing this for now, but willing to revisit if it seems like a very common need.

**Comment by minoraxis** [comment]
Thanks Austin! Def want to keep this conversation going. We have this in the backlog to investigate further. I think it would be a handy feature to have, but there's a lot of testing we'd want to do to find a solution that works across the board. We'd want to consider implications to readability, spacing between strokes, pixel-snapping — and how to deal with variable corner radiuses as @rektdeckard mentioned.

**Comment by AustinGil** [comment]
For sure. On one hand, Im sure you want to make sure your hard work is not wasted by icons coming out bad. On the other hand, if people can preview the icons while they make their edits, then it might not matter since they can see how their choices change things.

Anyway, it's a great project regardless. Thank you so much for the work you put into it. 

Since it's in the backlog already, do you want to close this issue?
