### ISSUE TITLE
Feature Request: Variable stroke width

### ISSUE THREAD

**Issue by mtmtwalker** [phosphor-icons/phosphor-home#26]
Thanks for making Phosphor icons open source, we love them. We really appreciate the attention to detail in retaining a clear consistency of style throughout the set as well as all the thoughtfulness put into their documentation and distribution.

We are currently using Phosphor in our web app at 16px and 20px for most icons, with some 24px and 32px icons for limited cases. We are having a little trouble getting the icon stroke width to look consistent across each size. Even experimenting with the various options (thin, light, regular etc.) we find that the bold 16px icons render a bit thin compared to larger icons of the same style. Additionally, we love the duotone set, but can't use this flexibly as the stroke weight is currently fixed.

We'd like to propose the idea of granular control of stroke width. Of course we recognise it may not be possible to render the icons properly and legibly at all stroke widths, but having some finer control might allow us to get consistency across icon sizes.

Another simpler idea may be to introduce a 'black' weight that helps us beef up icons at smaller sizes. 

Would love to know what you think. If you're on board with this change we're more than happy to submit a pull request.

Thanks again for all your work on this!

Mike and @callum

**Comment by minoraxis** [comment]
Thanks for notes Mike! I hear you and we definitely thought a lot about this. In building the system we took kind of a middle ground by custom-creating 6 weights that work out of the box while giving away the raw assets for designers to manipulate further (medium design effort, some control, some flexibility, medium system complexity — see chart below).

![custom-vs-variable](https://user-images.githubusercontent.com/14998128/108865197-f59fe700-75c0-11eb-99e2-c1b8f8eef43f.png)

What's wonderful about Feather and pure variable-type sets is the full flexibility in adjusting stroke width. However this comes at the cost you outlined, in the integrity of the glyph. For Phosphor, each weight is customized (e.g., optical fine-tuning in the dots, optical fine-tuning for readability, especially in Bold), so it's not set up to accommodate on-the-spot stroke adjustments.

All that said, there might be a world where your proposal gets layered on to the current approach. This can get messy though so we'll need to do some testing before we make a decision. In the meantime I'd suggest going in and beefing up or slimming down the strokes as needed.

Adding your other notes to the backlog:
• We'll consider a Black weight though Bold is already pushing the bounds of a 16px canvas. If we can maintain clarity while dropping some detail this might work, and it would be fun to have a super chunky weight.
• We realize the shortcomings of the Fill and Duotone weights, both being based off of the Regular stroke thickness. Perhaps there's a way we can decouple this parameter in the future.

Thanks and keep the feedback coming.

H

**Comment by mtmtwalker** [comment]
Thanks for the really detailed response Helena! It's useful to see your thinking behind the set and where it sits strategically compared to other icon sets. It all makes sense to me and I'm happy with what you've added to the backlog. Both seem challenging, but I look forward to seeing what you come up with! As you say, in the meantime we will experiment with the available widths and see how we can make things work. Thanks again for taking the time to reply in such detail.

Mike
