### ISSUE TITLE
Update Medium Icon

### ISSUE THREAD

**Issue by gupta-ji6** [phosphor-icons/phosphor-home#28]
**Describe the requested icon**
The [Medium](https://medium.com/) brand icon is outdated. I would really appreciate it if you could update it.

Thank you for building Phosphor Icons ✨

Read about the new Medium brand and logo guidelines [here](https://medium.design/logos-and-brand-guidelines-f1a01a733592).

**Screenshots**

<details>
  <summary>Medium Icon on Phosphor Icons</summary>
  
![medium-logo-duotone](https://user-images.githubusercontent.com/21218732/108168137-cdc20680-711c-11eb-9fb0-f1a42d91efda.png)

</details>

<details>
  <summary>New Medium Icon</summary>
  
![image](https://user-images.githubusercontent.com/21218732/108168204-e500f400-711c-11eb-9baa-009aabda3180.png)
![image](https://user-images.githubusercontent.com/21218732/108168233-f5b16a00-711c-11eb-8936-f079f6c879f0.png)

</details>

**Additional context**
[An introduction to Medium's evolved brand identity](https://blog.medium.com/a-more-expressive-medium-starting-with-medium-63b562206d8f)

**Comment by rektdeckard** [comment]
`MediumLogo` added in 1.2.0!

**Comment by gupta-ji6** [comment]
thank you!
