### ISSUE TITLE
Can we have a map of all icons code? So we can map them into a database?

### ISSUE THREAD

**Issue by e200** [phosphor-icons/phosphor-home#30]
I'm building a Flutter app and using this awesome icons package!

What I need is to set icons dynamic via database, but right now this isn't possible because we don't have each icon code mapped, thus, I can't make an API that provides the list of icons.

Could we have something like a json that we can use to map all icons into our apps? Thanks!

**Comment by rektdeckard** [comment]
Hey @e200! We have a flutter package already ([phosphor-flutter](https://github.com/phosphor-icons/phosphor-flutter)) in case you haven't noticed! It sounds like you might need something slightly different for your use-case though.

We generate a JSON file via IcoMoon which we include in the [asset kit](https://phosphoricons.com/assets/phosphor-icons.zip) with every release, but the character codes are not stable between versions. If you're content to stick with a fixed version of Phosphor, you can use that. We aren't planning on making a public API of our own any time soon.

**Comment by rektdeckard** [comment]
Just a heads up: we're going to be stabilizing icon codepoints starting with the next release, meaning you'll be able to get unicodes from the [@phosphor-icons/core](https://github.com/phosphor-icons/core) package, and it should be possible to integrate into the flutter package pretty easily.
