### ISSUE TITLE
Drawing icons

### ISSUE THREAD

**Issue by mtancoigne** [phosphor-icons/phosphor-home#31]
**Describe the requested icon**
It would be nice to have drawing-related icons : I'm building an app where people can trace shapes on a map and I came with these manually drawn icons (screenshot):
The downside of these is:
- They don't really fit with other phosphor icons
- They are SVGs, inlined in an `img` tag thus don't support color variations

Basically, I'd like the following icons:

- polygon shape
- multi-line shape

I haven't seen a way to combine icons (e.g.: a `ph-map-pin` with an upper `ph-plus`), these variants are welcome:

- ph-map-pin +
- ph-circle +
- polygon +
- multi-line +

**Screenshots**
![image](https://user-images.githubusercontent.com/1732268/114234834-9a169680-997f-11eb-8e79-f470446a24c2.png)

**Additional context**
If you're interested to add these and want a base, the [sources are available](https://gitlab.com/experimentslabs/garden-party/garden-party/-/tree/develop/public/ui). (I see there are some more outdated ones from when I wasn't yet using Phosphor :) )

I can also make a PR with an attempt to match your design.

Thanks for the good work, your set is refreshing :)

**Comment by rektdeckard** [comment]
Hey, sorry for the delay. I think we can add some of the design tool icons you're looking for, yes. We'll have to look and see where the case can be made for '+ variants', or if they're a bit too specific to your application.

**Comment by minoraxis** [comment]
Thanks for the suggestions @mtancoigne Working on these this weekend. Polygon and multiline should be fun :) Modifiers like "+" can get tricky in terms of readability but will take a look at those as well.

**Comment by mtancoigne** [comment]
Thanks @minoraxis! Have a good time !

**Comment by minoraxis** [comment]
We've added `bounding-box`, `line-segment`, `line-segments`, and `polygon` in v1.3.1!

**Comment by mtancoigne** [comment]
You're awesome ! Thanks !
