### ISSUE TITLE
Suggestions for icon Unicode.

### ISSUE THREAD

**Issue by l2zeo** [phosphor-icons/phosphor-home#32]
Hopefully Unicode has been added to the preview.

```
.ph-pencil-line:before {
    content: "\f130";
}
```

**Comment by rektdeckard** [comment]
Due to the way we generate the icon font, the character code mappings unfortunately aren't stable from one version to the next. Because of this, I don't like recommending this as a safe way to use the icons :/

In future we're going to try to move away from the icon font implementation altogether.
