### ISSUE TITLE
fast forward & rewind

### ISSUE THREAD

**Issue by emaschas** [phosphor-icons/phosphor-home#33]
Could you please add "Fast forward" and "Rewind" similar to "fast-forward-circle" and "rewind-circle" without the circle to complete the set of play / pause / stop / skip-forward / skip-back.
Thank you.

**Comment by rektdeckard** [comment]
Can do! Must have been an oversight, as I'm sure we meant to have those icons at launch.

**Comment by emaschas** [comment]
Many thanks....

**Comment by rektdeckard** [comment]
Added in v1.3.1!
