### ISSUE TITLE
Tree

### ISSUE THREAD

**Issue by straversi** [phosphor-icons/phosphor-home#34]
**Describe the requested icon**
A tree. For depicting nature.

**Screenshots**
![Screen Shot 2021-04-29 at 4 18 13 PM](https://user-images.githubusercontent.com/7411489/116629680-96cf5480-a906-11eb-8736-e02ebcb996a4.png)

Thanks!

**Comment by rektdeckard** [comment]
Love it. More nature and animals!

**Comment by amartshah** [comment]
Would love more environment and animal icons!

**Comment by rektdeckard** [comment]
v1.3.1 adds `cat`, `dog`, `fish`, `fish-simple`, `tree`, `tree-evergreen`, and others to the nature family!
