### ISSUE TITLE
GitLab Icon

### ISSUE THREAD

**Issue by mikerockett** [phosphor-icons/phosphor-home#35]
**Describe the requested icon**

An icon for the GitLab Logo.

**Screenshots**

![image](https://user-images.githubusercontent.com/4586280/116805887-bbefdd00-ab29-11eb-9af2-6ee66b081cad.png)

**Additional context**

Given the different line weights that could be applied, my design above uses a minimal version of the logo, without joining lines.

**Comment by rektdeckard** [comment]
`gitlab-logo` and `gitlab-logo-simple`  added in v1.3.1!

**Comment by mikerockett** [comment]
Looks great, thanks! 😀
