### ISSUE TITLE
Header Icon(s)

### ISSUE THREAD

**Issue by merriman-xyz** [phosphor-icons/phosphor-home#36]
**Describe the requested icon**
Header icon(s). Useful in editors when you want to insert a header.

**Screenshots**
- From the Bear notes app on Mac
![image](https://user-images.githubusercontent.com/67341535/116833799-36037e80-ab89-11eb-8b76-8c25a478ba70.png)

- From the Github editor
![image](https://user-images.githubusercontent.com/67341535/116833889-a6aa9b00-ab89-11eb-892e-abb1e3b0a171.png)

**Additional context**
An H in the style of the other edit icons would do the job. H1-H6 would be a plus.

**Comment by rektdeckard** [comment]
We'll see how it works with the subscript numbers, but should not be a problem to cover at least the `H`.

**Comment by rektdeckard** [comment]
`text-h` and -one through -six  added in v1.3.1!
