### ISSUE TITLE
Stripe Icon

### ISSUE THREAD

**Issue by ashconnell** [phosphor-icons/phosphor-home#37]
**Describe the requested icon**
We integrate with Stripe and have a section for users to configure their stripe settings etc. 

**Screenshots**
We were using MaterialDesignIcons.com, here's our settings screen before I started switching the icons over to Phosphor:

![image](https://user-images.githubusercontent.com/760516/117093241-bb627b00-ada3-11eb-9838-b3d58b90866f.png)

And here it is with Phosphor:

![image](https://user-images.githubusercontent.com/760516/117093294-de8d2a80-ada3-11eb-942b-41f7672a23d5.png)

**Comment by rektdeckard** [comment]
Dashboard looks great :) I think we can accommodate a Stripe logo.

**Comment by rektdeckard** [comment]
`stripe-logo`  added in v1.3.1!
