### ISSUE TITLE
Chevron Icons

### ISSUE THREAD

**Issue by ashconnell** [phosphor-icons/phosphor-home#38]
**Describe the requested icon**

You'll often see chevron's used for dropdown menu's, or buttons that go back and forward.
I tried to use the Phosphor arrow's, arrow-circle's and caret but these look a bit weird to me for these controls.

**Screenshots**

This is what we're currently using for a dropdown menu:

![image](https://user-images.githubusercontent.com/760516/117109244-b4e5fa80-adc7-11eb-8ffa-562112138daa.png)

And here we are using the Phosphor caret. It looks okay but I suspect chevrons would display nicer:

![image](https://user-images.githubusercontent.com/760516/117109415-f70f3c00-adc7-11eb-849c-472c3d98b9a8.png)

**Comment by rektdeckard** [comment]
What is you actual request here?

**Comment by ashconnell** [comment]
@rektdeckard i'm requesting basic chevrons for each direction. If you're unfamiliar, they're essentially arrows without the extra line:

![image](https://user-images.githubusercontent.com/760516/117149748-d6140e80-adfa-11eb-892d-93938fc9f85f.png)

**Comment by ashconnell** [comment]
I'm an idiot. I set our default to duotone right off the bat and I just realised the `Caret` icons are literally chevrons if you disable duotone :P
