### ISSUE TITLE
Magic wand icon

### ISSUE THREAD

**Issue by utkarshgill** [phosphor-icons/phosphor-home#39]
**Describe the requested icon**
I think a magic wand icon would be really useful. For places like adding filters in photos or transforming something magical.

**Screenshots**
If applicable, add screenshots to help illustrate the icon appearance.

<img width="162" alt="Screenshot 2021-05-11 at 2 13 13 AM" src="https://user-images.githubusercontent.com/46515280/117722254-748ae000-b1fe-11eb-855e-bfac76547cc0.png">

**Additional context**
Add any other context here.

**Comment by rektdeckard** [comment]
`magic-wand`  added in v1.3.1!
