### ISSUE TITLE
Microsoft brand icon

### ISSUE THREAD

**Issue by Morbden** [phosphor-icons/phosphor-home#40]
For the authentication form, I need some brands. the brands "Google" and "Apple" already exist, but "Microsoft" doesn't

**Comment by CodeDoctorDE** [comment]
i think you can  use simpleicons for that: https://simpleicons.org/

**Comment by rektdeckard** [comment]
We'll be adding a `windows-logo` in the next release, i.e.:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Windows_logo_-_2012.svg/120px-Windows_logo_-_2012.svg.png" />

The Microsoft logo, though, is so simple that it's probably already covered by the existing `squares-four` icon -- there's not much more we can do there 😄. We'll tag it so it's easier to locate on our website.

**Comment by rektdeckard** [comment]
`windows-logo`  added in v1.3.1!
