### ISSUE TITLE
Select icons

### ISSUE THREAD

**Issue by CodeDoctorDE** [phosphor-icons/phosphor-home#42]
**Describe the requested icon**
It would be cool if there are some select icons in this library.

**Screenshots**
https://materialdesignicons.com/icon/select-off
https://materialdesignicons.com/icon/select
https://materialdesignicons.com/icon/select-inverse
https://materialdesignicons.com/icon/select-all

**Additional context**
I'm switching from materialdesignicons to phosphor because I like the light icons :)

**Comment by rektdeckard** [comment]
Glad you like them, @CodeDoctorDE! 

`selection`, `selection-all`, `selection-background`, `selection-foreground`, `selection-inverse`, `selection-plus`, and `selection-slash` were just added in v1.3.1. hope you've got enough to choose from :)
