### ISSUE TITLE
Cookie (Privacy) Icon

### ISSUE THREAD

**Issue by RXminuS** [phosphor-icons/phosphor-home#43]
Needed an icon of a Cookie for our GRPC notice and was surprised to find Phosphor doesn't have one yet. Think there might be other icons related to privacy that could be cool to ad as well.

**Comment by tobias-fried-qatalog** [comment]
Can do! Adding this to the list for the next release.

**Comment by rektdeckard** [comment]
`cookie` added in v1.3.1!
