### ISSUE TITLE
Star Half

### ISSUE THREAD

**Issue by steve231293** [phosphor-icons/phosphor-home#44]
**Describe the requested icon**
Hello @author,

Could you please add Icon "star half" to library.

Thanks in advance!

**Screenshots**
If applicable, add screenshots to help illustrate the icon appearance.

[https://fontawesome.com/v5.15/icons/star-half-alt?style=solid](https://fontawesome.com/v5.15/icons/star-half-alt?style=solid)
[https://fontawesome.com/v5.15/icons/star-half?style=solid](https://fontawesome.com/v5.15/icons/star-half?style=solid)

**Additional context**
Add any other context here.

**Comment by rektdeckard** [comment]
`star-half` added in v1.3.1!
