### ISSUE TITLE
Icons for Different Events 

### ISSUE THREAD

**Issue by iamsahilvhora** [phosphor-icons/phosphor-home#45]
Icons for Different Events i.e. **Cake for Birthdays** & **Today Date Icon for Wedding Anniversaries**

![icons8-today-48](https://user-images.githubusercontent.com/7503466/121026159-7cb94980-c7c3-11eb-9c6d-20e1333e9f23.png)
![icons8-cute-cake-48](https://user-images.githubusercontent.com/7503466/121026165-7dea7680-c7c3-11eb-90bb-c067b8bd9e41.png)

**Comment by rektdeckard** [comment]
`calendar-check`, `calendar-plus`, and  `cake` just added in v1.3.1!
