### ISSUE TITLE
性别图标

### ISSUE THREAD

**Issue by limao6** [phosphor-icons/phosphor-home#46]
您好，我在使用的过程中经常会用到“男女性别”的图标，或者说male、female，使用次数比较频繁，希望能尽快添加到图标库，感谢！

**Comment by tobias-fried-qatalog** [comment]
`gender-female`, `gender-intersex`, `gender-male`, `gender-neuter`, `gender-nonbinary`, and `gender-transgender` added in v1.3.1!
