### ISSUE TITLE
Nice spinner/loading indicator

### ISSUE THREAD

**Issue by Kopyov** [phosphor-icons/phosphor-home#47]
**Describe the requested icon**
First of all want to say a huge THANK YOU for releasing this library, this is by far the most nice looking and perfectly designed icon set. Please keep maintaining it, it will for sure become more and more popular!

As per icon request, would be nice to have some nice loading indicator that can be animated with infinite rotation in CSS.

**Screenshots**
Something like this:

<img width="269" alt="Screenshot 2021-06-17 at 17 02 48" src="https://user-images.githubusercontent.com/17024224/122424880-5c417a00-cf8f-11eb-9c5d-2cc564c2a2e4.png">

**Comment by rektdeckard** [comment]
Thanks for the kind words! We do have a few loaders, check out `spinner` and `spinner-gap` -- but we'd be happy to add some more variety there if you don't see what you need.

**Comment by minoraxis** [comment]
Added `circle-notch` in 1.4!
