### ISSUE TITLE
tiktok

### ISSUE THREAD

**Issue by mozonpablo** [phosphor-icons/phosphor-home#48]
Hi guys,
Firs of all what a great library. We are dropping everything else and only using this from no on.
Thank you for making available to the public!
Any chance to create a TikTok icon to go along the other social media icons? It's the only icon we are missing right now.
Best regards,
Pablo

**Comment by rektdeckard** [comment]
Thanks so much, Pablo! `tiktok-logo` was just added in v1.3.1!

**Comment by mozonpablo** [comment]
You guys are amazing!

		
Pablo Monzon
CEO, WeFit
+6592726420  | ***@***.***
www.wetime.io  | Skype: pablomonzon
