### ISSUE TITLE
Singular and new icons

### ISSUE THREAD

**Issue by RichardBarrett** [phosphor-icons/phosphor-home#51]
**Describe the requested icon**
A collection of icons to extend what is already there plus a few new ones. I've put together the SVGs, they're contained in the attached ZIP file.

**Screenshots**
![icons](https://user-images.githubusercontent.com/1667234/125274854-b3016000-e351-11eb-8f19-86550241589c.jpg)

[icons.zip](https://github.com/phosphor-icons/phosphor-home/files/6800717/icons.zip)

**Comment by rektdeckard** [comment]
Thanks for the submission, @RichardBarrett! We've got a number of these covered already -- look for `align-top`, `align-bottom`, etc. We also have a few of these in the works already. Can you add some more context on the icons in the bottom row? What are they representing, and what's the use-case?

If you don't mind, we may modify/adapt some of these for the next release.

**Comment by RichardBarrett** [comment]
Hi there
To give you some context. I'm building a SaaS product and have found a few items missing pertaining to UI and form icons, which explains the button, text input and radio button icons; a gradient icon is also missing but I ran out of time.

I understand that you already have alignment and direction icons but they're doubled up. In order to keep the UI cleaner, i'd like to see singular versions for cleanliness. These icons look somewhat bulky/clunky in-situ.

I'll be sending through more icons for you to review very soon.

I hope that helps.

**Comment by rektdeckard** [comment]
Added `arrows-horizontal`, `arrows-vertical` `cursor-text`, `password`, `radio-button`, `textbox`, and simple versions of `align` icons in v1.4.0!
