### ISSUE TITLE
More Hamburger Icons

### ISSUE THREAD

**Issue by praveenjuge** [phosphor-icons/phosphor-home#52]
**Describe the requested icon**
Variants of the hamburger icon would be great addition I think. 
Some good use cases [described here](https://www.justinmind.com/blog/hamburger-menu/).

**Screenshots**
Here are some of my ideas:

<img width="1400" alt="CleanShot 2021-07-13 at 12 01 15@2x" src="https://user-images.githubusercontent.com/13696888/125402543-28147a00-e3d2-11eb-8ef9-ed9ffaaf39b6.png">

**Additional context**
I think providing some alternatives would be good for hamburger menu as it's one of the commonly used UI pattern in landing pages.
Absolutely love phosphor icons by the way. We are using it in our [production app](https://feedback.hellonext.co). Thanks.

**Comment by rektdeckard** [comment]
Wow, nice issue tracker! Great to see phosphor in use in the wild 🤸‍♂️
I think we can add a little variety to our offering... maybe add a literal hamburger too 🍔

Thanks for the suggestion!

**Comment by rektdeckard** [comment]
Added a literal `hamburger` in v1.4.0 :)

**Comment by praveenjuge** [comment]
Congrats on the 1.4.0 release, every icon looks incredible!

**Comment by minoraxis** [comment]
Thanks so much @praveenjuge! Going to close this issue for now as the examples you posted look a little too close to our text alignment icons. Please send more ideas our way if you have more use cases to cover.
