### ISSUE TITLE
Movie icons (Genres and others)

### ISSUE THREAD

**Issue by Teio07** [phosphor-icons/phosphor-home#54]
### Movie related icons
**Movie genres**
- Action
- Animation
- Biopic
- Comedy
- Crime
- Dance
- Disaster
- Drama
- Fantasy
- Film Noir
- Found Footage
- Historical
- Horror
- Musical
- Mystery
- Puzzle
- Romance
- Sci-Fi
- Sport
- Superhero
- Thriller
- War
- Western

**Misc**
- Pop-Corn
- Retro TV
- Script
- Clapper

I know some of them (like the Heart for Romance, the Knife for Thriller,...) already exists, but I just put them in the list just in case you guys had a better idea for those.

Of course, the icons don't have to be named like the genre for example the Western icon should probably be named Cactus but it would be cool to create a collection of these. For a movie theater website, a screenwriting app, or whatever related to movies.

**Screenshots to illustrate both how the icons could look like and their usage**

<img width="1408" alt="Capture d’écran 2021-07-18 à 19 29 17" src="https://user-images.githubusercontent.com/50293307/126076767-fa536282-7d02-49e4-b775-b04949b917e6.png">
<img width="1408" alt="Capture d’écran 2021-07-18 à 19 28 15" src="https://user-images.githubusercontent.com/50293307/126076765-7acd93b7-5a43-491b-b392-ba33e0ca45a9.png">

**Comment by Teio07** [comment]
@rektdeckard I tried making them with Figma and fit the Phosphoricon's style but I'm not sure they all fit together.

What do you think ?

To me, the superhero mask and the clown face are too big, the gangster with the hat looks too small and I'm not entirely sure that much shadow in his face fits the style of the other icons.

![MovieIcons](https://user-images.githubusercontent.com/50293307/127492432-3168ceb7-5fea-444b-9ee7-53b11ed1eae1.png)

**Comment by rektdeckard** [comment]
These look great @Teio07! Sorry it's taken me so long to respond. We'll take our own pass through some of these to see what's appropriate for the set. We probably won't end up implementing all of these, as we try to avoid diving too deep into specific product domains and prefer to cover the general cases first -- but I can say for sure that some of these are on the drawing board.

Over the next couple releases, we plan to add:
`alien`, `flying-saucer`  (sci-fi)
`mask`, `mask-theater` (superhero, drama)
`cactus` (western)
`television-retro` (classics)
`popcorn`
`script`

Existing icons that might be of use:
`baseball`, `basketball`, `football`, `soccer-ball`, `tennis-ball`, `volleyball` (sports)
`ghost` (horror)
`heart` (romance)
`knife` (crime)
`magic-wand`, (fantasy)
`magnifying-glass` (mystery)
`music-notes` (musical)
`puzzle-piece` (puzzle)
`sword` (adventure)

**Comment by rektdeckard** [comment]
Whoo boy. Added `alien`, `cactus`, `detective`, `film-slate`, `film-script`, `flying-saucer`, `mask-happy`, `mask-sad`, `popcorn`, `scroll`, `skull`, and possibly others that could be useful for you in v1.4.0!
