### ISSUE TITLE
Icon for opacity

### ISSUE THREAD

**Issue by RichardBarrett** [phosphor-icons/phosphor-home#55]
**Describe the requested icon**
Please add an icon for opacity.

**Screenshots**
![image](https://user-images.githubusercontent.com/1667234/126142345-b4169718-7c36-4d12-8078-9998492ddae7.png)

**Additional context**
It would be great if you could add an icon for opacity.

**Comment by rektdeckard** [comment]
`circle-half`, `intersect` icons might be what you need

**Comment by RichardBarrett** [comment]
I've taken a look and they're not quite right. However, I did notice that the drop-half icon could have a horizontal variant; for example:
![image](https://user-images.githubusercontent.com/1667234/126225894-2c4598dd-7874-4122-9510-6a77c6cded08.png)

**Comment by rektdeckard** [comment]
Added `drop-half-bottom` in v1.4.0!
