### ISSUE TITLE
Small issue with hover effect on underlined links in the website

### ISSUE THREAD

**Issue by AugustoNicola** [phosphor-icons/phosphor-home#58]
**Describe the bug**
When hovering over the links in the last section of the website, their underline effect dissappears (as intentioned). However, if the mouse is slowly moved down until it reaches just the same height of the line, the component will enter a loop of hovering and un-hovering, due to the underline expanding the hover hitbox.

**To Reproduce**
1. Hover over any anchor tag with the `main-link` class
2. Slowly drag the mouse down until it unhovers
3. With some luck, the mouse will be positioned just at the same height as the underline, causing the bug.

**Expected behavior**
The link should either hover or unhover, your choice 😄

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 90.0.2 (64-bit)

**Comment by rektdeckard** [comment]
Fixed.
