### ISSUE TITLE
https://unpkg.com/phosphor-icons link is broken

### ISSUE THREAD

**Issue by dgastudio** [phosphor-icons/phosphor-home#60]
is redirecting to https://rio-unknown-store.productwiz.io/

Unknown Store
Variant Wizard does not know the store you are trying to use the app with

Please try opening up the app again through your Shopify admin. If you are still experiencing any issues, please contact us at support-rio@productwiz.io. We will resolve this!

Pro tip: If you have bookmarked the app, please ensure that the ?shop= query is present in your bookmarked URL. An example would be https://app.productwiz.io/?shop=loja.myshopify.com.

**Comment by dgastudio** [comment]
seems working fine now

**Comment by tobias-fried-qatalog** [comment]
They were hacked. This would probably have affected a large number of hosted packages on the platform. https://twitter.com/DonFeebs/status/1427333203627548674
