### ISSUE TITLE
Nigerian naira icon

### ISSUE THREAD

**Issue by bot101** [phosphor-icons/phosphor-home#63]
**Describe the requested icon**
I love your icons and started using them recently. I am designing an application targeted at the Nigerian market and would love to see the icon for the Nigerian currency (Naira) added to the icon set

**Screenshots**
![naira_icon](https://user-images.githubusercontent.com/8009733/130662577-dbc6aa81-20fe-40be-aed9-9154c563ef9a.png)

**Comment by rektdeckard** [comment]
Added `currency-ngn` in v1.4.0!
