### ISSUE TITLE
Blog & pricing related icons.

### ISSUE THREAD

**Issue by socrates-qatalog** [phosphor-icons/phosphor-home#65]
**Describe the requested icon**
Hi, we are looking for icons to use in our website. Specifically something to signify our blog & pricing pages.

**Screenshots**
Something like:
![image](https://user-images.githubusercontent.com/77860056/130992205-3a220ded-c559-4f50-a825-28a3412538da.png) 

Perhaps something to signify pricing like a tag or coins:
![image](https://user-images.githubusercontent.com/77860056/130992323-14c8c4eb-5b22-49d4-bbae-385be69c6fcf.png)
![image](https://user-images.githubusercontent.com/77860056/130992362-d00fc328-a45b-494c-9dcc-c191cf726944.png)

Thank you,
Not Aristoteles

**Comment by rektdeckard** [comment]
@socrates-qatalog hey bud, I'm closing this since we already cover these with `note-pencil`, `tag`, and a number of currency-related icons.
