### ISSUE TITLE
Programming language icons

### ISSUE THREAD

**Issue by SydneyJupiters** [phosphor-icons/phosphor-home#69]
I would for some programming language/tool icons e.g HTML, CSS, Javascript etc. It could just be the popular ones :)

**Comment by rektdeckard** [comment]
We're aiming to expand the existing file icons to inlude:

`file-archive`
`file-audio`
`file-cloud`
`file-code`
`file-css`
`file-csv`,
`file-doc`,
`file-html`,
`file-image`
`file-jpg`
`file-js`
`file-jsx`
`file-lock`
`file-png`
`file-ppt`
`file-rs`
`file-ts`
`file-tsx`
`file-video`
`file-vue`
`file-xls`
`file-zip`

**Comment by rektdeckard** [comment]
Added a whole bunch of file types (including programming languages) in v1.4.0!
