### ISSUE TITLE
request new icon

### ISSUE THREAD

**Issue by cucxuong** [phosphor-icons/phosphor-home#7]
Hi teams,
Thanks for your amazing icons.
But I hope you can add more icon such as handshake or something similar with the deal meaning.

**Comment by rektdeckard** [comment]
Definitely see that being useful! We'll see what we can do.

**Comment by RichardBarrett** [comment]
I have a few icons to request, some of which I think are mandatory for icons libraries.

- Bold
- Italic
- Underline
- Strikethrough/Line through

- arrow-line-middle-vertical
- arrow-line-middle-horizontal

![image](https://user-images.githubusercontent.com/1667234/99006937-f58a5700-258e-11eb-95aa-e3591f8fb356.png)

**Comment by rektdeckard** [comment]
> I have a few icons to request, some of which I think are mandatory for icons libraries.

These icons are already designed and will be in the next release! Next time start a new issue with a separate request. Moved to #9.

**Comment by rektdeckard** [comment]
Handshake has been added to all libraries as of `v1.1.0` 🤝
