### ISSUE TITLE
Add to playlist and queue icons for music player app

### ISSUE THREAD

**Issue by abeyshiferaw0** [phosphor-icons/phosphor-home#71]
Add to playlist and queue icons for music player app

<img width="40" alt="Screen Shot 2021-09-24 at 7 27 56 PM" src="https://user-images.githubusercontent.com/85179138/134667252-b2593e9a-171a-480c-97a5-83b9c5b088b4.png">

**Comment by rektdeckard** [comment]
Added `music-notes-plus` in v1.4.0! And `list-plus` should fit for the queue 👍
