### ISSUE TITLE
Stamp icon

### ISSUE THREAD

**Issue by mtmtwalker** [phosphor-icons/phosphor-home#76]
**Describe the requested icon**
I'd love to see a stamp icon like the one shown below. Asana uses it to signify 'Approval request'. It could also be used for a stamp feature in a product - like Figjam does.

**Screenshots**

_Asana_
<img width="33" alt="image" src="https://user-images.githubusercontent.com/40828227/137152675-b4277e80-9919-4588-b1f3-3e11cec8e099.png"> 

_Figjam_
<img width="53" alt="image" src="https://user-images.githubusercontent.com/40828227/137153132-729a39e7-22ba-4a6f-b498-8d8bcee38687.png">

**Additional context**
There's no need for the box around the stamp like in the examples shown above.

**Comment by rektdeckard** [comment]
Added `stamp` in v1.4.0!
