### ISSUE TITLE
Connect/Plug icon

### ISSUE THREAD

**Issue by ax2mx** [phosphor-icons/phosphor-home#77]
**Description**
The icon should indicate the state of being _"connected/plugged to"_ in various meanings, it also may be used as a metaphor for the action _"to connect/plug"_. For instance, indicate that _"connection to database/server has been established"._

Of course, the icon should be designed in pair with the opposite state _"disconnected"_ and action _"to disconnect from"_. 

**Screenshots**
This is a good example of how it might look like:

[vscode-codicons](https://microsoft.github.io/vscode-codicons/)
<img width="257" alt="VS Code codicons" src="https://user-images.githubusercontent.com/27804799/137522496-cbad5b85-1618-4353-8e12-ea56958409d8.png">

**Additional context**
Since the idea of being _"connected/disconnected"_ is basic for web development, I hope it will be designed and added to icon set very soon.
Thanks in advance!

**Comment by rektdeckard** [comment]
Added `plug`, `plugs`, `plugs-connected` in v1.4.0!
