### ISSUE TITLE
Switch Camera Icon

### ISSUE THREAD

**Issue by bekirytm** [phosphor-icons/phosphor-home#78]
Describe the requested icon
I think the camera switch icon would be really helpful. An icon that is hard to find on other sites as well.

Screenshots
![switchcamera](https://user-images.githubusercontent.com/36936802/137912175-4d0c1cf9-b6ae-4616-a5ca-8101bb2fcbd0.png)

I hope you add. :)

**Comment by rektdeckard** [comment]
Added `camera-rotate` in v1.4.0!
