### ISSUE TITLE
More of a question regarding whitespace

### ISSUE THREAD

**Issue by BMCwebdev** [phosphor-icons/phosphor-home#8]
Hey there. Love this library. I'm wondering, our design system is built on the idea that no elements have whitespace, and that is the job of our layout components. It looks like all these icons contain their own whitespace. Is there a way I'd be able to batch convert all of these to removed the excess whitespace? Thank you so much!

**Comment by rektdeckard** [comment]
@BMCwebdev Thanks! Unfortunately there's no quick fix for your use-case... We build 'padding' directly into the path info of the SVGs to make them visually consistent in size. If every icon just filled the square on it's largest axis, you'd have visual inconsistencies.

**Comment by rektdeckard** [comment]
I would definitely direct you to read my partner's [article on the subject](https://uxdesign.cc/7-principles-of-icon-design-e7187539e4a2) and why we chose to do this, and [not to preach, but] why you might want to to it in your design system. 

As an example, a square-shaped icon that fits a 32 x 32 canvas would completely fill it, and look much larger than a circular icon that fits a 32 x 32 canvas. How much do you size up the circle to make them look visually the same size? That's what we figure out beforehand.

**Comment by KaKi87** [comment]
Hi,

I need to align the `play` icon to the left edge of its parent.

How do I do that ?

Thanks
