### ISSUE TITLE
Apple Podcasts icon

### ISSUE THREAD

**Issue by mauricekleine** [phosphor-icons/phosphor-home#80]
**Describe the requested icon**
I'd like to use the Apple Podcasts icon through Phosphor

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/10089969/140907427-43d4a0be-7e77-41cf-a41b-59acecfdac1c.png)

**Additional context**
We're building a podcasting app and we'd like to use this logo to link to the Apple Podcast page relating to a podcast

**Comment by rektdeckard** [comment]
Added `apple-podcasts-logo` in v1.4.0!
