### ISSUE TITLE
Google Podcasts icon

### ISSUE THREAD

**Issue by mauricekleine** [phosphor-icons/phosphor-home#81]
Describe the requested icon
I'd like to use the Google Podcasts icon through Phosphor

Screenshots
![afbeelding](https://user-images.githubusercontent.com/10089969/140907660-b2b7eb6c-2827-456f-9c98-54f26c72c458.png)

Additional context
We're building a podcasting app and we'd like to use this logo to link to the Google Podcast page relating to a podcast

**Comment by rektdeckard** [comment]
Added `google-podcasts-logo`, `apple-podcasts-logo` in v1.4.0!

**Comment by mauricekleine** [comment]
Awesome, thanks a bunch @rektdeckard!
