### ISSUE TITLE
Currency icon - Kazakhstan tenge

### ISSUE THREAD

**Issue by YerlenZhubangaliyev** [phosphor-icons/phosphor-home#83]
**Describe the requested icon**
Currency icon - Kazakhstan tenge

**Screenshots**
![Tenge](https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Kazakhstani_tenge_symbol.svg/160px-Kazakhstani_tenge_symbol.svg.png)

**Additional context**
[Wikipedia.](https://en.wikipedia.org/wiki/Kazakhstani_tenge)

**Comment by rektdeckard** [comment]
Added `currency-kzt` in v1.4.0!
