### ISSUE TITLE
Website: Add flutter example

### ISSUE THREAD

**Issue by CodeDoctorDE** [phosphor-icons/phosphor-home#89]
![image](https://user-images.githubusercontent.com/20452814/147332528-204e0ca0-41d7-4fc2-b37d-24ac52f16308.png)
Currently there is only react, vue and html/css. Please add an example for flutter.

A template can be:
```
Icon(PhosphorIcons.example)
```

**Comment by rektdeckard** [comment]
Will do, thanks @CodeDoctorDE. We plan to rework this section soon.

**Comment by rektdeckard** [comment]
Added Flutter snippets in 4137a8b5c198a14861aabe74104ae05a48802dcb, more thorough rework to happen later.
